
// (1) Fibonacci Sequence is : 1, 1, 2, 3, 5, 8, 13, 21, 34,......
// (2) Calculate the value of number N item of Fibonacci Sequence.
// (3) The number N is generated by using random method, the value is between 1~20;
import java.util.Scanner;

public class Q3 {
    public static void main(String[] args) {
        // (2)input N and output the N term
        Scanner num = new Scanner(System.in);
        System.out.println("Please input the term of the sequence you want to calculate:");
        int input = num.nextInt();
        System.out.println("The " + input + " term in a Fibonacci Sequence is " + fibo(input));
        // (3)the number N is generated by using random method, the value is between
        // 1~20
        int ran = (int) Math.random() * 19 + 1;
        System.out.println("The random term " + ran + " in a Fibonacci Sequence is " + fibo(ran));

    }

    public static int fibo(int c) {
        c -= 1;
        int count[];
        count = new int[500];
        count[0] = 1;
        count[1] = 1;

        for (int i = 2; i <= c; i++) {
            count[i] = count[i - 1] + count[i - 2];
        }
        return count[c];

    }
}
